{
 "title": "Chainguard Adoption",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kind",
    "query": {
     "query": "label_values(container_image_container_info,kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Chainguard Containers %",
   "type": "piechart",
   "description": "The number of containers in the cluster that are using Chainguard or Non-Chainguard images.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (value) (\n      container_image_container_info{kind=~\"$kind\"}\n    * on (digest) group_left (value)\n      label_replace(\n        container_image_label{key=\"dev.chainguard.package.main\"},\n        \"value\",\n        \"Chainguard\",\n        \"\",\n        \"\"\n      )\n  or on (digest)\n    label_replace(container_image_container_info{kind=~\"$kind\"}, \"value\", \"Non-Chainguard\", \"\", \"\")\n)\n",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Chainguard Images %",
   "type": "piechart",
   "description": "The number of distinct images (by digest) in the cluster that are Chainguard or based on Chainguard.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (value) (\n      max by (digest) (container_image_container_info{kind=~\"$kind\"})\n    * on (digest) group_left (value)\n      label_replace(\n        container_image_label{key=\"dev.chainguard.package.main\"},\n        \"value\",\n        \"Chainguard\",\n        \"\",\n        \"\"\n      )\n  or on (digest)\n    label_replace(max by (digest) (container_image_container_info{kind=~\"$kind\"}), \"value\", \"Non-Chainguard\", \"\", \"\")\n)\n",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Containers % By Source",
   "type": "piechart",
   "description": "The number of containers in the cluster that are using Chainguard or Non-Chainguard images.",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (value) (\n      container_image_container_info{kind=~\"$kind\"}\n    * on (digest) group_left (value)\n        container_image_label{key=\"org.opencontainers.image.source\"}\n  or on (digest)\n    label_replace(container_image_container_info{kind=~\"$kind\"}, \"value\", \"<UNKNOWN>\", \"\", \"\")\n)\n",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Chainguard Containers % By Main Package",
   "type": "piechart",
   "description": "The number of containers in the cluster that are using Chainguard or Non-Chainguard images.",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (value) (\n      container_image_container_info{kind=~\"$kind\"}\n    * on (digest) group_left (value)\n        container_image_label{key=\"dev.chainguard.package.main\",value!=\"\"}\n)\n",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Chainguard % By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\n(\n  count(container_image_container_info * on(digest) group_left max(container_image_label{key=\"dev.chainguard.package.main\"}) by (key,digest)) by (exported_namespace)\n  or\n  count(container_image_container_info) by (exported_namespace) * 0\n)\n/\ncount(container_image_container_info) by (exported_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Chainguard Containers",
   "type": "table",
   "description": "Containers that are not running Chainguard images or images based on Chainguard images.",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "    max by (kind, exported_namespace, name, image, digest) (container_image_container_info{kind=~\"$kind\"})\n  * on (digest) group_left (value)\n    label_replace(container_image_label{key=\"dev.chainguard.package.main\"}, \"value\", \"Chainguard\", \"\", \"\")\nor on (digest)\n  max by (kind, exported_namespace, name, image, digest) (container_image_container_info{kind=~\"$kind\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Chainguard Images",
   "type": "table",
   "description": "The count of each non-Chainguard image in the cluster. Excludes the tag and digest to provide a count of each distinct image repository.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "count by (image,value) (\nlabel_replace(\ncontainer_image_container_info{kind=~\"$kind\"}\n  * on (digest) group_left (value)\n    label_replace(container_image_label{key=\"dev.chainguard.package.main\"}, \"value\", \"Chainguard\", \"\", \"\")\nor on (digest)\n  container_image_container_info{kind=~\"$kind\"}, \"image\", \"$1\", \"image\", \"^([^/]+/[^:@]+|[^:@]+).*$\"))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}